<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="5" result="Failed" total="5" passed="3" failed="1" inconclusive="0" skipped="1" asserts="4" engine-version="3.7.0.0" clr-version="4.0.30319.42000" start-time="2017-11-14 14:10:39Z" end-time="2017-11-14 14:10:40Z" duration="1.149419">
  <command-line><![CDATA["C:\Work\Test Solutions\NUnitDemo\ConsoleApp\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe"  "C:\Work\Test Solutions\NUnitDemo\ConsoleApp\ConsoleApp.Test\bin\Debug\ConsoleApp.Test.dll" /result:"C:\Work\Test Solutions\NUnitDemo\ConsoleApp\ConsoleApp.Test\bin\Debug\Result.xml" ]]></command-line>
  <test-suite type="Assembly" id="0-1011" name="ConsoleApp.Test.dll" fullname="C:\Work\Test Solutions\NUnitDemo\ConsoleApp\ConsoleApp.Test\bin\Debug\ConsoleApp.Test.dll" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.464482" total="5" passed="3" failed="1" warnings="0" inconclusive="0" skipped="1" asserts="4">
    <environment framework-version="3.9.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.1.7601.65536" platform="Win32NT" cwd="C:\Windows\system32" machine-name="R90BWA9C" user="eqruuwq" user-domain="ERICSSON" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="C:\Windows\system32" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.6.1" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="576" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1012" name="ConsoleApp" fullname="ConsoleApp" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.433445" total="5" passed="3" failed="1" warnings="0" inconclusive="0" skipped="1" asserts="4">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="0-1013" name="Test" fullname="ConsoleApp.Test" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.431880" total="5" passed="3" failed="1" warnings="0" inconclusive="0" skipped="1" asserts="4">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="0-1000" name="Class1" fullname="ConsoleApp.Test.Class1" classname="ConsoleApp.Test.Class1" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.427121" total="5" passed="3" failed="1" warnings="0" inconclusive="0" skipped="1" asserts="4">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-suite type="ParameterizedMethod" id="0-1002" name="TestAdd" fullname="ConsoleApp.Test.Class1.TestAdd" classname="ConsoleApp.Test.Class1" runstate="Runnable" testcasecount="1" result="Passed" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.317312" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="1">
            <properties>
              <property name="Category" value="AdditionTests" />
            </properties>
            <test-case id="0-1001" name="TestAdd()" fullname="ConsoleApp.Test.Class1.TestAdd()" methodname="TestAdd" classname="ConsoleApp.Test.Class1" runstate="Runnable" seed="381003389" result="Passed" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.304311" asserts="1" />
          </test-suite>
          <test-suite type="ParameterizedMethod" id="0-1010" name="TestAddException" fullname="ConsoleApp.Test.Class1.TestAddException" classname="ConsoleApp.Test.Class1" runstate="Runnable" testcasecount="1" result="Passed" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.044332" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="1">
            <test-case id="0-1009" name="TestAddException()" fullname="ConsoleApp.Test.Class1.TestAddException()" methodname="TestAddException" classname="ConsoleApp.Test.Class1" runstate="Runnable" seed="1219291936" result="Passed" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.044211" asserts="1" />
          </test-suite>
          <test-suite type="ParameterizedMethod" id="0-1004" name="TestAddFail" fullname="ConsoleApp.Test.Class1.TestAddFail" classname="ConsoleApp.Test.Class1" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.034732" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="1">
            <properties>
              <property name="Category" value="AdditionTests" />
            </properties>
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-case id="0-1003" name="TestAddFail()" fullname="ConsoleApp.Test.Class1.TestAddFail()" methodname="TestAddFail" classname="ConsoleApp.Test.Class1" runstate="Runnable" seed="317531992" result="Failed" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.034672" asserts="1">
              <failure>
                <message><![CDATA[  Expected: 6
  But was:  60
]]></message>
                <stack-trace><![CDATA[   at ConsoleApp.Test.Class1.TestAddFail() in C:\Work\Test Solutions\NUnitDemo\ConsoleApp\ConsoleApp.Test\Class1.cs:line 33
]]></stack-trace>
              </failure>
              <assertions>
                <assertion result="Failed">
                  <message><![CDATA[  Expected: 6
  But was:  60
]]></message>
                  <stack-trace><![CDATA[   at ConsoleApp.Test.Class1.TestAddFail() in C:\Work\Test Solutions\NUnitDemo\ConsoleApp\ConsoleApp.Test\Class1.cs:line 33
]]></stack-trace>
                </assertion>
              </assertions>
            </test-case>
          </test-suite>
          <test-suite type="ParameterizedMethod" id="0-1006" name="TestAddGreater" fullname="ConsoleApp.Test.Class1.TestAddGreater" classname="ConsoleApp.Test.Class1" runstate="Runnable" testcasecount="1" result="Passed" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.017883" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="1">
            <properties>
              <property name="Category" value="GreaterTests" />
            </properties>
            <test-case id="0-1005" name="TestAddGreater()" fullname="ConsoleApp.Test.Class1.TestAddGreater()" methodname="TestAddGreater" classname="ConsoleApp.Test.Class1" runstate="Runnable" seed="677076174" result="Passed" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.017804" asserts="1" />
          </test-suite>
          <test-suite type="ParameterizedMethod" id="0-1008" name="TestAddIgnore" fullname="ConsoleApp.Test.Class1.TestAddIgnore" classname="ConsoleApp.Test.Class1" runstate="Ignored" testcasecount="1" result="Skipped" label="Ignored" site="SetUp" start-time="2017-11-14 14:10:40Z" end-time="2017-11-14 14:10:40Z" duration="0.001666" total="1" passed="0" failed="0" warnings="0" inconclusive="0" skipped="1" asserts="0">
            <properties>
              <property name="_SKIPREASON" value="Skipping TestAddIgnore for Demo purpose" />
            </properties>
            <reason>
              <message><![CDATA[Skipping TestAddIgnore for Demo purpose]]></message>
            </reason>
            <test-case id="0-1007" name="TestAddIgnore()" fullname="ConsoleApp.Test.Class1.TestAddIgnore()" methodname="TestAddIgnore" classname="ConsoleApp.Test.Class1" runstate="Runnable" seed="1334695141" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
              <reason>
                <message><![CDATA[OneTimeSetUp: Skipping TestAddIgnore for Demo purpose]]></message>
              </reason>
            </test-case>
          </test-suite>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>